theme = "hugo-black-and-light-theme"
languageCode = "en-us"
title = "Tim's R Notes"
baseurl = "/"
author = "Tim Sallay"
paginate = 10
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
  post = "/post/:year/:month/:day/"

[params]
  sitename = "Tim's R Notes"

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
